site_name: Naver Playground
site_url: https://won983212.github.io/mc-naver-playground
theme:
  name: material
  language: en
  font:
    text: NanumBarunGothic
markdown_extensions:
  - admonition
extra_css:
  - https://hangeul.pstatic.net/hangeul_static/css/nanum-barun-gothic.css
nav:
  - 서버 접속 방법: index.md
  - 게임 플레이: game-play.md
  - 게임 시스템:
    - 전투: game-play/combat.md
    - 지역보호 및 파티: game-play/protection.md
    - 음성 채팅: game-play/voice.md
  - 쉐이더 사용 방법: shader.md
  - 설치된 모드 목록: mods.md
