site_name: Naver Playground
site_url: https://won983212.github.io/mc-naver-playground

theme:
  name: material
  language: en
  font:
    text: NanumBarunGothic

markdown_extensions:
  - admonition

extra_css:
  - https://hangeul.pstatic.net/hangeul_static/css/nanum-barun-gothic.css

nav:
  - 서버 접속 방법: index.md
  - 음성 채팅: voice.md
  - 쉐이더 사용 방법: shader.md
